# Generated by Django 3.2.3 on 2021-06-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencylastexchange',
            name='exchanged_currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currencylastexchange',
            name='source_currency',
            field=models.CharField(max_length=3),
        ),
    ]
