# Generated by Django 3.2.3 on 2021-06-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0002_auto_20210530_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='adapter',
            field=models.CharField(choices=[('exchange_rate.views.FixerAdapter', 'Fixer'), ('exchange_rate.views.MockAdapter', 'Mock')], max_length=50),
        ),
    ]
